name: "Upload Unit"
description: "Uploads a unit to Cratecode, as well as any included lessons."
author: "Cratecode"
branding:
    icon: upload
    color: blue
inputs:
    key:
        required: true
        description: "The API Key."
    manifest:
        required: true
        description: "The manifest file to use to upload."
        default: "manifest.json"
runs:
    using: "node16"
    main: "dist/index.js"
